### ISSUE TITLE
Link to latest binary?

### ISSUE THREAD

**Issue by kaihendry** [CyCoreSystems/go-meteor#4]
Can quite figure it out: `curl -LO https://github.com/CyCoreSystems/go-meteor/releases/latest/download/meteor-dockerfilegen_linux_amd64` is a 404

Don't want to install a Golang env in my https://github.com/unee-t/frontend/blob/master/buildspec.yml

**Comment by kaihendry** [comment]
Figured it out with thanks to #goreleaser on Gophers

    curl -LO $(curl -s https://api.github.com/repos/CyCoreSystems/go-meteor/releases/latest | jq -r '.assets[] |  .browser_download_url | select(contains("_linux_"))')

**Comment by Ulexus** [comment]
Am I referencing that incorrect URL somewhere?  The README links you to the Github Releases page, which has correct links.

**Comment by kaihendry** [comment]
Need a programmatic way if I am going to integrate this into my CI's buildspec.yml

**Comment by Ulexus** [comment]
The links for releases _are_ predictable, but what you have is also fine.
